UK_ROOT ?= $(PWD)/../../unikraft
UK_LIBS ?= $(PWD)/../../libs
DEPS := $(UK_LIBS)/pthread-embedded:$(UK_LIBS)/newlib:$(UK_LIBS)/lwip:$(UK_LIBS)/mimalloc:$(UK_LIBS)/tinyalloc
LIBS := $(DEPS)

all:
	@+make -C $(UK_ROOT) A=$(PWD) L=$(LIBS)

$(MAKECMDGOALS):
	@+make -C $(UK_ROOT) A=$(PWD) L=$(LIBS) $(MAKECMDGOALS)
